version: 2
updates:
  # Configuration for minor and patch updates
  # NuGet packages (.NET projects)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "Automatic_version_update_dependabot"

# Root-level configuration for automerge and versioning
automerge:
  enable: true
  allow:
    - dependency-type: "all"
    - update-type: "minor"
    - update-type: "patch"
    - update-type: "pin"
    - update-type: "digest"

versioning-strategy: auto