version: 2
updates:
  # Configuration for minor and patch updates
  # NuGet packages (.NET projects)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "Automatic_version_update_dependabot"
    automerge: true
    automerge-types: ["minor", "patch", "pin", "digest"]
    # Optional: Set version requirement for automerge
    versioning-strategy: auto
    
