name: Release
on: [push, pull_request]
#on:
#  push:
#    branches:
#      - [master, main]  # Only trigger on main branch pushes
## qqqq want regular releases so maybe not release branch but would be nice as part of pr to have a branch have its own gh-deploy
## qqqq this is on merge into release branch and we need to generate a release package and a gh page
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for Semantic Release to analyze commit history

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          
        
      - name: Install Semantic Release Packages
        run: |
         npm install -D \
         semantic-release \
         @semantic-release/changelog \
         @semantic-release/git \
         @semantic-release/commit-analyzer \
         @semantic-release/release-notes-generator
         
         
         
         
         
##configured with .releaseseec
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
        
